### ISSUE TITLE
When can we customize LED projector headlamps

### ISSUE THREAD

**Issue by lm339** [teslamotors/light-show#28] opened 2021-12-27 15:22 UTC
When can we customize LED projector headlamps

**Comment by anatolinicolae** [comment] 2021-12-28 10:27
Duplicate of #1 perhaps?

**Comment by JVB-Tesla** [comment] 2022-01-06 02:16
>> When can we customize LED projector headlamps

Agree this would be awesome. Significant engineering required to make this happen ... join us!

https://www.tesla.com/careers/search/

Software Validation Engineer, Body Controls
System Integration Engineer, Body Controls
System Validation Engineer, Body Controls
Embedded Software Engineer, Body Controls

**Closed by JVB-Tesla** 2022-01-06 02:16 UTC

**Comment by vish1** [comment] 2022-08-25 23:21
Any progress on this feature?
