### ISSUE TITLE
Error "Unknown file format, expected FSEQ v2.0". Newer XLight uses FSEQ files V2.2 Incompatible with Tesla's V2.0 Requirement

### ISSUE THREAD

**Issue by xingxu21** [teslamotors/light-show#67] opened 2023-03-27 05:04 UTC
Users are getting Validation Error:  Incompatible with newer versions of XLight Generating Error "Unknown file format, expected FSEQ v2.0" when validating the generated FSEQ file despite following the README.md file precisely. The root cause of this occurs due to XLight defaulting to FSEQ versions 2.2 while Tesla vehicles require version 2.0 without Xlight giving users options to set specifically 2.0. 

# Overview
Multiple people ([Lazy-Double-6538](https://www.reddit.com/r/TeslaLightShow/comments/11x0ftj/fseq_validation_error/?utm_source=share&utm_medium=web2x&context=3), [BradB132](https://www.reddit.com/r/TeslaLightShow/comments/11x0ftj/comment/jdkdgwi/?utm_source=share&utm_medium=web2x&context=3), [Relevant_Resolve9671](https://www.reddit.com/r/TeslaLightShow/comments/11x0ftj/comment/jdokzfr/?utm_source=share&utm_medium=web2x&context=3), [foxbat7777](https://www.reddit.com/r/TeslaLightShow/comments/romw6s/comment/ht4s296/?utm_source=share&utm_medium=web2x&context=3)) in the last 7 days including myself have reported validation errors despite following the directions precisely on the `README.md` with regards to step 4 `select V2 Uncompressed`. This issues affects users using XLight downloaded on the app store with version 2023.04. 

The newer updates of XLights uses fseq files V2.2 of fseq rather than Tesla's required version of V2.0, with the Tesla and validator files rejecting newer versions. Any user attempting to create light shows on a mac with Xlights downloaded with the app store (and likely future versions of xlights on windows) will no longer be able to develop without resorting to older versions of xlight.  

# Workaround
**A temporary workaround can be achieved by [downgrading to 2022.01 version](https://dankulp.com/xlights/archive/) of XLight until this bug is resolved through XLight and Tesla via a software update.**

# Issue 
As stated above, multiple users including myself have noticed that despite having the V2 Uncompressed option selected in sequence settings, the `.fsq` file synthesized fails the validation script `validator.py` issuing the error `"Unknown file format, expected FSEQ v2.0"`. The root cause of this issue exists for the 2023-04 downloaded through the app store as recommended in the [Xlights releases documentation](https://xlights.org/releases/). This fittingly corresponds to the timing of the complaints from above. 

# Replication
When downloading xlights on OSX via the app store for version 2023-04, clicking select V2 Uncompressed under the setup instructions, and following the steps listed under `Creating a New Sequence` in the `README.md` file, and saving the file, once you run the validator on the `<file.fseq>`, the `"Unknown file format, expected FSEQ v2.0"` pops up.  A look at the fseq binary files  (visible by printing the values of `start, minor, major = struct.unpack("<HBB", file.read(4))` from the validator) will indicate that the fseq uses version 2.2 and not version 2.0. 

This can also be proven by using any of the provided example fseq files provided by Tesla. Without modifications, the file passes validation. After making one change and saving, the example file fails the validation. 

# Suggestion/ Conclusion
It is in Tesla's interest to either internally update vehicles to support FSEQ v2.2 or have the developers of XLight to allow users to use `V2.0` (note this is different from the current V2 uncompressed selection that leaves the minor version ambiguous) explicitly in the UI sequence settings of XLights. Otherwise this bug will frustrate future users without the knowledge of downgrading as a workaround in their efforts to develop custom light shows.

**Comment by cmastudios** [comment] 2023-03-27 06:38
The vehicle side parser doesn't actually check the version number, so I would expect v2.2 files should still play correctly.

**Comment by cmastudios** [comment] 2023-03-27 06:41
I would expect V2.2 files should still play correctly in vehicle. I think the validator might need to be updated.

**Comment by xingxu21** [comment] 2023-03-27 07:26
That's what I thought at first too, but it seems like the vehicle's internal validator is also rejecting the `.fseq` file. The `custom light show` selection was still greyed out in my 2022 vehicle running version 2023.2.12 using the V2.2 files. This leads me to believe an over the air update is necessary. I was also unable to update the vehicles software to investigate [hacba0](https://www.reddit.com/r/TeslaLightShow/comments/121gx31/do_not_update_xlights/)'s claim that the file would still work despite failing the validator

**Comment by cmastudios** [comment] 2023-03-27 07:51
The custom selection should only be greyed if the USB is not connected (or doesn't contain a LightShow folder), otherwise there should be an error message.

**Comment by spaceXrace** [comment] 2023-03-27 11:55
Based on [this comment](https://www.reddit.com/r/TeslaLightShow/comments/11x0ftj/comment/jdokzfr/?utm_source=share&utm_medium=web2x&context=3), I have a suspicion that XLights for macOS changed more about the FSEQ files than XLights for Windows.

That would explain why some can play their files on the car, while others can not.

The file I have from 2023.04 Windows starts with PSEQ ([according to this document it's always PSEQ](https://github.com/Cryptkeeper/fseq-file-format)). Meanwhile the comment mentioned above states theirs starts with FSEQ.

If anyone has the latest version on macOS, it would be great if you can send me your .fseq and .xsq: hvcraft.yt@gmail.com

**Comment by cmastudios** [comment] 2023-03-27 17:44
I have the latest version on Mac and this is the only difference I see (using old xlights show folder and existing xsq):
```diff
@@ -1,5 +1,5 @@
-00000000: 5053 4551 9800 0202 2000 3000 0000 a504  PSEQ.... .0.....
-00000010: 0000 3200 0000 0000 03ad 30ba dbf7 0500  ..2.......0.....
+00000000: 5053 4551 9800 0002 2000 3000 0000 a504  PSEQ.... .0.....
+00000010: 0000 3200 0000 0000 4908 503f b2db 0500  ..2.....I.P?....
```
Seems only relevant thing changing is the minor version number

**Comment by spaceXrace** [comment] 2023-03-28 19:19
I think we can then assume that Mac files work fine in the car as well. 
The comment I mentioned before claiming their file on Mac is FSEQ1 is wrong. It’s PSEQ & V2.2, as it should be.

**Comment by tram01** [comment] 2023-04-01 02:11
I'm getting the following error too - Unknown file format, expected FSEQ v2.0

when I plug in the drive with fseq and mp3 file, I get the error invalid number of channels. surprisingly, despite this error custom light show worked partially once, it played half the song, and after that it does not work on any of my teslas. 

I need this custom light show to work ASAP, any help is appreciated. I'm attaching the fseq and sequence file here. [](url)
[Archive.zip](https://github.com/teslamotors/light-show/files/11128227/Archive.zip)

**Comment by xingxu21** [comment] 2023-04-01 02:24
I still haven't had luck playing V2.2 version as its greyed out on my tesla so i want to say there's more than just a header version modification. @tram01 can you confirm that you downgraded Xlights to the version I specified above?

**Comment by tram01** [comment] 2023-04-01 02:34
I didn't downgrade Xlight, I'm using the latest version

**Comment by spaceXrace** [comment] 2023-04-01 03:57
Thank you for sharing the file. 
you can downgrade to 2023.1 to get a working file

**Comment by cmastudios** [comment] 2023-04-01 18:16
> when I plug in the drive with fseq and mp3 file, I get the error **invalid number of channels**. surprisingly, despite this error custom light show worked partially once, it played half the song, and after that it does not work on any of my teslas.

Opened your file in xLights 2023.05.1 on Mac. Clicked save, checked the .fseq and it had 0xc0 (196) channels which was causing this error.
I went to the sequencer tab, hit render all, hit save. Checked the .fseq and it has 0x30 (48) channels now which will pass the validator on the car.

```
$ xxd lightshow.fseq | head
00000000: 5053 4551 9000 0202 2000 c400 0000 d42e  PSEQ.... .......
$ xxd lightshow.fseq | head
00000000: 5053 4551 9000 0202 2000 3000 0000 d42e  PSEQ.... .0.....
```

**Comment by tram01** [comment] 2023-04-01 18:39
Can you send me the sequence file and fseq pls Do I need to still downgrade xLight? Sent from my iPhoneOn Apr 1, 2023, at 1:16 PM, Connor Monahan ***@***.***> wrote:﻿

when I plug in the drive with fseq and mp3 file, I get the error invalid number of channels. surprisingly, despite this error custom light show worked partially once, it played half the song, and after that it does not work on any of my teslas.

Opened your file in xLights 2023.05.1 on Mac. Clicked save, checked the .fseq and it had 0xc0 (196) channels which was causing this error.
I went to the sequencer tab, hit render all, hit save. Checked the .fseq and it has 0x30 (48) channels now which will pass the validator on the car.
$ xxd lightshow.fseq | head
00000000: 5053 4551 9000 0202 2000 c400 0000 d42e  PSEQ.... .......
$ xxd lightshow.fseq | head
00000000: 5053 4551 9000 0202 2000 3000 0000 d42e  PSEQ.... .0.....

**Comment by cmastudios** [comment] 2023-04-01 18:47
Should not need to downgrade xlights, but lmk if the steps I provided don't fix your issue. [lightshow.fseq.zip](https://github.com/teslamotors/light-show/files/11130323/lightshow.fseq.zip)

**Comment by tram01** [comment] 2023-04-02 16:38
@cmastudios didn't work for me. were you able to play in your Tesla ?

**Comment by EdwinOtten** [comment] 2024-02-07 10:39
**Update as of February 2024:**
It looks like both issues described above have been fixed in validator.py:
1. `Unknown file format, expected FSEQ v2.0`
   - Fixed in #68 
2. `Expected 48 channels, got 200`
   - Fixed in #86 

I think this issue can be closed. @xingxu21 @tram01 can you confirm this issue is resolved for you as well when using the latest version of XLights and the latest `validator.py`?

**Comment by IDMJ24** [comment] 2024-02-11 16:03
I tried xlights 2024.02 and 2023.01 versions.  The sequencer worked inside the xlights program.  But they both gave errors in the standalone validator and in the Tesla drive as error.  The current master file on line may also be incompatible with FSEQ version 2.0.  I need to create a Lightshow for a charity.  Can someone help?  Thanks.

**Comment by spaceXrace** [comment] 2024-02-11 17:52
I cannot reproduce your issue in 2024.02, and 2023.01 is known to be working. You probably didn't set the FSEQ Format to V2 Uncompressed in xLights preferences.

The issue mentioned in the original comment is fixed.

**Comment by IDMJ24** [comment] 2024-02-11 20:53
Hello:

Thanks for helping me.  I did set as V2 Uncompressed.  These are the screen shots and files that are causing errors.  Please advise what I was doing wrong.

Thanks

Jimmy Chan
469.408.8838

From: spaceXrace ***@***.***>
Date: Sunday, February 11, 2024 at 11:53 AM
To: teslamotors/light-show ***@***.***>
Cc: IDMJ24 ***@***.***>, Comment ***@***.***>
Subject: Re: [teslamotors/light-show] Error "Unknown file format, expected FSEQ v2.0". Newer XLight uses FSEQ files V2.2 Incompatible with Tesla's V2.0 Requirement (Issue #67)

I cannot reproduce your issue in 2024.02, and 2023.01 is known to be working. You probably didn't set the FSEQ Format to V2 Uncompressed in xLights preferences.

The issue mentioned in the original comment is fixed.

**Comment by EdwinOtten** [comment] 2024-02-22 21:01
@IDMJ24 did you use the latest version of `validator.py` from the `master` branch?

**Closed** 2024-10-21 03:35 UTC
